### ISSUE TITLE
fix readme link: pecorino-email @lasagnalove

### ISSUE THREAD

**Issue by patmejia** [Lasagna-Love-Portal/bechamel-api#14]
logging in order to i remember to do fix this later. or, anyone available
thanks

**Comment by emmanolan** [comment]
updated this and have a PR waiting approval: https://github.com/Lasagna-Love-Portal/bechamel-api/pull/17

**Comment by mattkuznicki-ll** [comment]
Confirmed resolved in https://github.com/Lasagna-Love-Portal/bechamel-api/pull/17
