### ISSUE TITLE
Securing User Data: Concealing the Password Field in JSON Responses

### ISSUE THREAD

**Issue by patmejia** [Lasagna-Love-Portal/bechamel-api#19]
Extracting @mattkuznicki-ll's important question from code 👇
`model/LasagnaLoveUser.go, Lines 13-14:
```
// This overrides the default marshaling of the structure to JSON, removing the password field value.
// It has the unfortunate side effect of leaving an empty string entry in the generated JSON
// which leaks out to users, but does allow the use of the same struct for GETting and POSTing user profiles.
//
// Better ideas are welcomed.
```

**Comment by mattkuznicki-ll** [comment]
@patmejia this is addressed in https://github.com/Lasagna-Love-Portal/bechamel-api/pull/18

**Comment by patmejia** [comment]
I have ideas, but need clarity on your insightful proposal first!

Below are some thoughts for potential actions: 

1. Identify the issue: the password field, though empty, is exposed in the JSON response.
2. Suggest using Go's `json:"-"` tag to hide the `Password` field during JSON serialization.
3. This change will render the `Password` field invisible in the JSON response.
4. Override the `MarshalJSON` method to handle POST and PUT operations, which need the password.
5. Implement a new `MarshalJSON` method using an anonymous struct mirroring `LasagnaLoveUser`, excluding `Password`.
6. Include an `Alias` field as a `LasagnaLoveUser` alias to reuse fields without redeclaration.
7. Tag the `Password` field as `json:"password,omitempty"` to exclude it from JSON if empty.
8. This approach allows inclusion of `Password` in POST and PUT, but not in GET.
9. Introduce a `Validate()` method to confirm presence and correctness of all required fields prior to operations.
10. These modifications enhance security, streamline JSON responses, and maintain `LasagnaLoveUser` struct's flexibility.
11. Request team feedback and suggestions for further improvement.

**Comment by mattkuznicki-ll** [comment]
Resolved in https://github.com/Lasagna-Love-Portal/bechamel-api/pull/18, closing.
